/* ==========================================================================
   LUXORA — Dummy data layer (products, categories, reviews)
   No backend. Everything here is static demo data.
   ========================================================================== */

const COLOR_SWATCH = {
  Black: "#111111",
  White: "#ffffff",
  Grey: "#8a8a8a",
  Blue: "#2f3e6b",
  Beige: "#d8c6a8",
  Olive: "#5c5c3d",
  Charcoal: "#3a3a3a",
  Rust: "#a8532b",
};

function img(seed, w = 700, h = 900) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

const PRODUCTS = [
  {
    id: "p1",
    name: "Premium Oversized T-Shirt",
    gender: "men",
    category: "T-Shirts",
    price: 699,
    originalPrice: 999,
    rating: 4.6,
    reviews: 238,
    badge: "Best Seller",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey"],
    images: [img("luxora-tee-1"), img("luxora-tee-2"), img("luxora-tee-3")],
    features: [
      "Premium cotton fabric",
      "Comfortable oversized fit",
      "Breathable material",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A heavyweight cotton tee cut for a relaxed, oversized silhouette. Built for everyday wear with a fabric hand that feels far more premium than the price tag suggests.",
  },
  {
    id: "p2",
    name: "Classic Casual Shirt",
    gender: "men",
    category: "Shirts",
    price: 999,
    originalPrice: 1399,
    rating: 4.4,
    reviews: 162,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "White", "Beige"],
    images: [img("luxora-shirt-1"), img("luxora-shirt-2"), img("luxora-shirt-3")],
    features: [
      "100% breathable cotton",
      "Tailored regular fit",
      "Wrinkle-resistant weave",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A go-to casual shirt with a tailored regular fit and a soft cotton weave — smart enough for the office, easy enough for the weekend.",
  },
  {
    id: "p3",
    name: "Relaxed Cargo Pants",
    gender: "men",
    category: "Cargo",
    price: 1199,
    originalPrice: 1699,
    rating: 4.5,
    reviews: 194,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Olive", "Black", "Beige"],
    images: [img("luxora-cargo-1"), img("luxora-cargo-2"), img("luxora-cargo-3")],
    features: [
      "Durable cotton-twill fabric",
      "Six-pocket utility design",
      "Relaxed tapered fit",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "Utility-driven cargo pants in a durable cotton twill, with a relaxed tapered leg and six functional pockets for everyday carry.",
  },
  {
    id: "p4",
    name: "Premium Hoodie",
    gender: "men",
    category: "Hoodies",
    price: 1499,
    originalPrice: 2199,
    rating: 4.7,
    reviews: 311,
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Charcoal", "Grey"],
    images: [img("luxora-hoodie-1"), img("luxora-hoodie-2"), img("luxora-hoodie-3")],
    features: [
      "350 GSM brushed fleece",
      "Kangaroo pocket",
      "Ribbed cuffs & hem",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A heavyweight 350 GSM fleece hoodie with a brushed interior for everyday warmth, finished with ribbed cuffs and a structured hood.",
  },
  {
    id: "p5",
    name: "Slim Fit Jeans",
    gender: "men",
    category: "Jeans",
    price: 1299,
    originalPrice: 1799,
    rating: 4.3,
    reviews: 147,
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    images: [img("luxora-jeans-1"), img("luxora-jeans-2"), img("luxora-jeans-3")],
    features: [
      "Stretch denim fabric",
      "Slim tapered fit",
      "Reinforced stitching",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "Stretch denim jeans cut close through the thigh and tapered at the ankle, built to move with you without losing its shape.",
  },
  {
    id: "p6",
    name: "Essential Cotton T-Shirt",
    gender: "women",
    category: "T-Shirts",
    price: 599,
    originalPrice: 799,
    rating: 4.5,
    reviews: 205,
    badge: "",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Beige"],
    images: [img("luxora-wtee-1"), img("luxora-wtee-2"), img("luxora-wtee-3")],
    features: [
      "Soft combed cotton",
      "Classic regular fit",
      "Pre-shrunk fabric",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A wardrobe staple in soft combed cotton — a clean regular fit that layers well and holds its shape wash after wash.",
  },
  {
    id: "p7",
    name: "Premium Polo T-Shirt",
    gender: "men",
    category: "T-Shirts",
    price: 799,
    originalPrice: 1099,
    rating: 4.4,
    reviews: 128,
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Rust"],
    images: [img("luxora-polo-1"), img("luxora-polo-2"), img("luxora-polo-3")],
    features: [
      "Pique cotton knit",
      "Ribbed collar & cuffs",
      "Regular fit",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A pique-knit polo with a ribbed collar and clean placket — smart-casual essential for warm-weather days.",
  },
  {
    id: "p8",
    name: "Casual Linen Shirt",
    gender: "men",
    category: "Shirts",
    price: 1099,
    originalPrice: 1499,
    rating: 4.2,
    reviews: 96,
    badge: "",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "White", "Olive"],
    images: [img("luxora-linen-1"), img("luxora-linen-2"), img("luxora-linen-3")],
    features: [
      "Breathable linen blend",
      "Relaxed comfort fit",
      "Lightweight for warm days",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A lightweight linen-blend shirt with a relaxed fit, made to breathe through warm days without wrinkling apart.",
  },
  {
    id: "p9",
    name: "Women's Boyfriend Hoodie",
    gender: "women",
    category: "Hoodies",
    price: 1399,
    originalPrice: 1999,
    rating: 4.6,
    reviews: 173,
    badge: "Best Seller",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Beige"],
    images: [img("luxora-whoodie-1"), img("luxora-whoodie-2"), img("luxora-whoodie-3")],
    features: [
      "Brushed fleece interior",
      "Relaxed boyfriend fit",
      "Drop-shoulder silhouette",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "An easy, drop-shoulder hoodie in brushed fleece — designed to be borrowed-from-a-friend comfortable.",
  },
  {
    id: "p10",
    name: "Women's High-Rise Jeans",
    gender: "women",
    category: "Jeans",
    price: 1349,
    originalPrice: 1899,
    rating: 4.5,
    reviews: 141,
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    images: [img("luxora-wjeans-1"), img("luxora-wjeans-2"), img("luxora-wjeans-3")],
    features: [
      "High-rise waistband",
      "Stretch denim fabric",
      "Straight leg fit",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "High-rise stretch denim in a clean straight leg — an everyday fit designed to sit comfortably and move easily.",
  },
  {
    id: "p11",
    name: "Utility Cargo Joggers",
    gender: "women",
    category: "Cargo",
    price: 1249,
    originalPrice: 1699,
    rating: 4.3,
    reviews: 88,
    badge: "",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Olive", "Grey"],
    images: [img("luxora-jogger-1"), img("luxora-jogger-2"), img("luxora-jogger-3")],
    features: [
      "Cotton-blend twill",
      "Elasticated cuffs",
      "Multi-pocket design",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "Jogger-cut cargo pants with elasticated cuffs and utility pockets — built for movement without sacrificing structure.",
  },
  {
    id: "p12",
    name: "Kids' Graphic T-Shirt",
    gender: "kids",
    category: "T-Shirts",
    price: 449,
    originalPrice: 599,
    rating: 4.5,
    reviews: 64,
    badge: "New",
    sizes: ["XS", "S", "M"],
    colors: ["White", "Blue", "Black"],
    images: [img("luxora-kids-1"), img("luxora-kids-2"), img("luxora-kids-3")],
    features: [
      "Soft cotton fabric",
      "Fun graphic print",
      "Comfortable regular fit",
      "Machine washable",
      "Quality checked",
    ],
    description:
      "A soft cotton graphic tee built for play — durable stitching and a fade-resistant print that survives the wash.",
  },
];

const CATEGORIES = [
  { key: "Men", label: "Men's Fashion", image: img("luxora-cat-men", 600, 700), filter: { gender: "men" } },
  { key: "Women", label: "Women's Fashion", image: img("luxora-cat-women", 600, 700), filter: { gender: "women" } },
  { key: "T-Shirts", label: "T-Shirts", image: img("luxora-cat-tshirts", 600, 700), filter: { category: "T-Shirts" } },
  { key: "Shirts", label: "Shirts", image: img("luxora-cat-shirts", 600, 700), filter: { category: "Shirts" } },
  { key: "Jeans", label: "Jeans", image: img("luxora-cat-jeans", 600, 700), filter: { category: "Jeans" } },
  { key: "Cargo", label: "Cargo Pants", image: img("luxora-cat-cargo", 600, 700), filter: { category: "Cargo" } },
  { key: "Hoodies", label: "Hoodies", image: img("luxora-cat-hoodies", 600, 700), filter: { category: "Hoodies" } },
  { key: "New", label: "New Arrivals", image: img("luxora-cat-new", 600, 700), filter: { badge: "New" } },
];

const NAV_CATEGORIES = ["Men", "Women", "Kids", "T-Shirts", "Shirts", "Jeans", "Cargo", "Hoodies", "New Arrivals", "Offers"];

const REVIEWS = [
  { name: "Rahul", city: "Chennai", rating: 5, text: "The quality feels much more premium than the price. Genuinely surprised by the fabric." },
  { name: "Priya", city: "Bangalore", rating: 5, text: "Loved the oversized fit and delivery was fast. Ordering another one already." },
  { name: "Aakash", city: "Hyderabad", rating: 4, text: "Great fit and the stitching feels solid. Sizing runs true, no surprises." },
  { name: "Sneha", city: "Mumbai", rating: 5, text: "My go-to brand now — the hoodie is soft and hasn't lost shape after washes." },
];

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}
